print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/Jon/Desktop/E_Project/Game/Assets/3) Models/Astronaut.ma"`)
{		
	file -o "/Users/Jon/Desktop/E_Project/Game/Assets/3) Models/Astronaut.ma";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/Jon/Desktop/E_Project/Game/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/Jon/Desktop/E_Project/Game/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/Jon/Desktop/E_Project/Game/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
